Add requirements.txt file
harikanani/AutomateInstaPyBot pull request #20
Opened 2021-03-11 20:49 UTC by Akash20x

## Related Issue
Add requirements.txt f
ile
Closes: #19 

### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

### Screenshots
Put any screenshot(s) of the project here.

2021-03-16 07:50 UTC, harikanani requested changes
Have extra packages that are not used in a project

2021-03-16 10:02 UTC, Akash20x commented
Please check this now

2021-03-17 06:15 UTC, harikanani reviewed
Looks Good for merge 😃 !

2021-03-17 06:15 UTC, harikanani approved these changes

2021-03-17 06:16 UTC, harikanani approved these changes

2021-03-17 06:26 UTC, merged